name: Update gist with WakaTime stats
on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: waka-box
        uses: ./.github/
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 1c7dd49583d9b24af05f2b1cbfab554a
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
